version: "3.9"

services:
######## mysql dev #######
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "quizformacao"
      MYSQL_USER: "qf"
      MYSQL_PASSWORD: "qf123"
      MYSQL_ROOT_PASSWORD: "qf123"
    ports:
      - "3306:3306"
